; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Ayttm
AppVerName=Ayttm 0.4.2-6
AppPublisherURL=http://ayttm.sourceforge.net
AppSupportURL=http://ayttm.sourceforge.net
AppUpdatesURL=http://ayttm.sourceforge.net
DefaultDirName={pf}\Ayttm
DefaultGroupName=Ayttm
LicenseFile=C:\Program Files\ayttm\COPYING
InfoAfterFile=C:\Program Files\ayttm\README.WIN32

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop icon"; GroupDescription: "Additional icons:"
Name: "quicklaunchicon"; Description: "Create a &Quick Launch icon"; GroupDescription: "Additional icons:"; Flags: unchecked

[Files]
Source: "C:\Program Files\ayttm\ayttm.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\setup.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\README.WIN32"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\COPYING"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libcharset-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libcrypto-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libgdk_pixbuf-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libgdk-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libgettextlib-0-12-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libgettextpo-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libgettextsrc-0-12-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libglib-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libgmodule-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libgobject-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libgpgme-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libgthread-2.0-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libgtk-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libiconv-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libintl-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libjasper-1-700-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libjpeg-62.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libltdl-3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libssl-0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\exchndl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\libXpm-noX4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\etc\ayttmrc"; DestDir: "{app}\etc"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\sounds\Send.au"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\sounds\BuddyLeave.au"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\sounds\Receive.au"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\sounds\BuddyArrive.au"; DestDir: "{app}\sounds"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\lib\gdk-pixbuf\loaders\libpixbufloader-jpeg.dll"; DestDir: "{app}\lib\gdk-pixbuf\loaders"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\smileys\Console Smileys\*.*"; DestDir: "{app}\smileys\Console Smileys"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\smileys\Giles Smiles\*.*"; DestDir: "{app}\smileys\Giles Smiles"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\aim-toc.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\aim-toc.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\autotrans.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\autotrans.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\icq-toc.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\icq-toc.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\import_everybuddy.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\import_everybuddy.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\import_gaim.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\import_gaim.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\import_gnomeicu.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\import_gnomeicu.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\importicq.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\importicq.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\importlicq.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\importlicq.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\irc.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\irc.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\jabber.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\jabber.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\middle.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\middle.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\msn2.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\msn2.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\notes.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\notes.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\rainbow.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\rainbow.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\smiley-themer.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\smiley-themer.la"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\yahoo2.dll"; DestDir: "{app}\modules"; Flags: ignoreversion
Source: "C:\Program Files\ayttm\modules\yahoo2.la"; DestDir: "{app}\modules"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[INI]
Filename: "{app}\Ayttm.url"; Section: "InternetShortcut"; Key: "URL"; String: "http://ayttm.sourceforge.net"

[Icons]
Name: "{group}\Ayttm"; Filename: "{app}\Ayttm.exe"
Name: "{group}\Ayttm on the Web"; Filename: "{app}\Ayttm.url"
Name: "{userdesktop}\Ayttm"; Filename: "{app}\Ayttm.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\Ayttm"; Filename: "{app}\Ayttm.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\setup.bat"; Parameters: "{app}"
Filename: "{app}\Ayttm.exe"; Description: "Launch Ayttm"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: files; Name: "{app}\Ayttm.url"

