#!/bin/sh
if [ X"$CC" = X ]
then
	CC=gcc-2
	export CC
fi
if [ X"$CXX" = X ]
then
	CXX=g++-2
	export CXX
fi
if [ X"$msnative_struct" = X ]
then
   case `$CC --version | sed -e 's,\..*,.,' -e q` in
      2.)
        if $CC -v --help 2>/dev/null | grep fnative-struct >/dev/null; then
          msnative_struct='-fnative-struct'
        fi
        ;;
      *)
        if $CC -v --help 2>/dev/null | grep ms-bitfields >/dev/null; then
          msnative_struct='-mms-bitfields'
        fi
        ;;
  esac
  export msnative_struct
fi

export LIBS="/target/lib/dirent.lib libltdl/libltdl.a libproxy/libproxy.a /target/lib/gtk.lib /target/lib/gdk.lib /target/lib/gmodule-2.0.lib /target/lib/glib-2.0.lib /target/lib/intl.lib /target/lib/iconv.lib -lwinmm -lws2_32 -lwst -lmsvcrt"
cd ..
dlltool --export-all --output-def ayttm.def src/*.o src/gtk/*.o libproxy/*.o
dlltool --dllname ayttm.exe --def ayttm.def --output-lib libayttm.a
dlltool --dllname ayttm.exe --output-exp ayttm.exp --def ayttm.def
${CXX} -mno-cygwin $msnative_struct -I/target/include -I/usr/include/mingw -I/usr/include/w32api -I/target/include/glib -I/target/include/glib-2.0 -I/usr/local/include -I/opt/include -I../ -I/usr/include/w32api -I/usr/include -D_REENTRANT -Wall -g -I.. -I./libproxy -o ayttm.exe -Wl,--subsystem,windows,--base-file,ayttm.base ayttm.exp src/*.o src/gtk/*.o ${LIBS}
dlltool --dllname ayttm.exe --base-file ayttm.base --output-exp ayttm.exp --def ayttm.def
${CXX} -mno-cygwin $msnative_struct -I/target/include -I/usr/include/mingw -I/usr/include/w32api -I/target/include/glib -I/target/include/glib-2.0 -I/usr/local/include -I/opt/include -I../ -I/usr/include/w32api -I/usr/include -D_REENTRANT -Wl,--subsystem,windows -Wall -g -I.. -I./libproxy -o ayttm.exe ayttm.exp src/*.o src/gtk/*.o ${LIBS}

